#!/bin/bash
 
# DNF Configuration
echo -e "# Added for speed:\nfastestmirror=True\nmax_parallel_downloads=10\ndefaultyes=True\nkeepcache=True" >> /etc/dnf/dnf.conf
 
# System Update
dnf update

# Enable RPM Fusion
dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfreerelease-$(rpm -E %fedora).noarch.rpm
dnf groupupdate core
 
# Adding Flatpaks
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
 
# Install Media Codecs
dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-
gstreamer-plugin
dnf groupupdate sound-and-video
 
# Install VirtualBox
curl -LO "https://download.virtualbox.org/virtualbox/6.1.34/VirtualBox-6.1-6.1.34_150636_fedora36-2.x86_64.rpm"
rpm -Uvh VirtualBox-6.1-6.1.34_150636_fedora36-2.x86_64.rpm
usermod -aG vboxusers $USER

 
# Install Docker
dnf -y install dnf-plugins-core
dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
dnf install docker-ce docker-ce-cli containerd.io docker-compose-plugin
groupadd docker
usermod -aG docker $USER

# Install Docker Desktop
curl -LO "https://desktop.docker.com/linux/main/amd64/docker-desktop-4.9.0-x86_64.rpm?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64"
dnf install ./docker-desktop-4.9.0-x86_64.rpm

# Install Kubernetes
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Install kind
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
chmod +x ./kind
mv ./kind /usr/local/bin/

# Install k3s
curl -sfL https://get.k3s.io | sh -

# Install minikube
grep -E --color 'vmx|svm' /proc/cpuinfo
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
sudo mkdir -p /usr/local/bin/
sudo install minikube /usr/local/bin/

# Install Lens
curl -LO "https://api.k8slens.dev/binaries/Lens-5.5.3-latest.20220602.2.x86_64.rpm"
rpm -Uvh Lens-5.5.3-latest.20220602.2.x86_64.rpm

# Installing Ansible
dnf install ansible

# Add Hashicorp Repo
dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

# Install Terraform
dnf -y install terraform

# Install Vault
dnf -y install vault

# Install Vagrant
dnf -y install vagrant

# Install AWS
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install

# Install ZSH
dnf install zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
grep $USER /etc/passwd
chsh -s $(which zsh)
grep $USER /etc/passwd

# https://www.sitepoint.com/zsh-tips-tricks/
# https://unix.stackexchange.com/questions/30168/how-to-enable-reverse-search-in-zsh
